env:
  global:
    # BEGIN: pipenv requirements to ignore virtual environment and create virtualenv (.venv forlder) inside the script folder
    - PIPENV_VENV_IN_PROJECT=true
    - PIPENV_IGNORE_VIRTUALENVS=1

language: python
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run python -m pytest --cov=task_script_utils --cov-branch
