name: Publish

on:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-python@v3
      with:
        python-version: 3.7

    - name: Build package
      run: |
        python3 -m pip install --upgrade build
        python3 -m build

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: ${{ secrets.ARTIFACTORY_USER }}
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}
        repository_url: ${{ secrets.ARTIFACTORY_URL }}      